version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: maintenance_influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=maintenance-org
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=maintenance-token-secret-key-12345
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped
    networks:
      - maintenance-network

  # Optional: InfluxDB UI (if you want a separate UI)
  chronograf:
    image: chronograf:1.10
    container_name: maintenance_chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
    networks:
      - maintenance-network
    restart: unless-stopped

volumes:
  influxdb-storage:
  influxdb-config:

networks:
  maintenance-network:
    driver: bridge
